version: "3.7"
networks:
    demo:
        name: demo
services:
    mongodb:
        image: mongo:4.0.4
        container_name: mongodb
        restart: always      
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin
            - MONGO_INITDB_DATABASE=admin
        ports:
        - "27017:27017"
        command: mongod
        volumes:
        - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        networks:
        - demo
    backenddemo:
        build: .
        container_name: bedemo
        restart: always   
        networks:
        - demo
        environment:
            WAIT_HOSTS: mongodb:27017        
        ports:
        - 3000:3000